// =============================================
// DADOS FALSOS - INVENTÁRIO ARBÓREO ANDRADAS
// Um árvore para cada categoria de botão
// =============================================

const MOCK_TREES = [

    // ── LOCAL DE PLANTIO ──────────────────────────

    {
        id: 1001,
        latitude: '-22.068100',
        longitude: '-46.573500',
        logradouro: 'Rua XV de Novembro',
        referencia: 'Em frente ao banco',
        localPlantio: 'calcada',
        especie: 'Tipuana tipu',
        certeza: 'certeza',
        porte: 'grande',
        tronco: 'grosso',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'nenhuma',
        mesPoda: '8',
        dataUltimaPoda: '2025-08-15',
        observacoes: 'Árvore localizada na calçada principal da Rua XV. Boa copa, sem problemas visíveis.',
        timestamp: Date.now() - 86400000 * 30,
        dataAtualizacao: Date.now() - 86400000 * 5,
        status: 'saudavel'
    },
    {
        id: 1002,
        latitude: '-22.067800',
        longitude: '-46.574100',
        logradouro: 'Praça da Matriz',
        referencia: 'Ao lado da igreja',
        localPlantio: 'praca',
        especie: 'Jacaranda mimosifolia',
        certeza: 'certeza',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'limpeza',
        mesPoda: '6',
        dataUltimaPoda: '2025-06-10',
        observacoes: 'Árvore na Praça da Matriz, muito bonita quando flora. Precisa de poda de limpeza.',
        timestamp: Date.now() - 86400000 * 28,
        dataAtualizacao: Date.now() - 86400000 * 3,
        status: 'atencao'
    },
    {
        id: 1003,
        latitude: '-22.069000',
        longitude: '-46.572800',
        logradouro: 'Avenida Brasil',
        referencia: 'No canteiro central',
        localPlantio: 'canteiro',
        especie: 'Handroanthus albus',
        certeza: 'certeza',
        porte: 'grande',
        tronco: 'grosso',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'nenhuma',
        mesPoda: '3',
        dataUltimaPoda: '2025-03-20',
        observacoes: 'Ipê-amarelo no canteiro central da Av. Brasil. Floresce em setembro.',
        timestamp: Date.now() - 86400000 * 25,
        dataAtualizacao: Date.now() - 86400000 * 2,
        status: 'saudavel'
    },
    {
        id: 1004,
        latitude: '-22.067200',
        longitude: '-46.575000',
        logradouro: 'Rua Marechal Deodoro',
        referencia: 'Frente à padaria',
        localPlantio: 'privada',
        especie: 'Ficus benjamina',
        certeza: 'certeza',
        porte: 'grande',
        tronco: 'grosso',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: ['galhos_secos'],
        interferencia: ['muros_telhados'],
        intervencao: 'adequacao',
        mesPoda: '9',
        dataUltimaPoda: '2025-09-05',
        observacoes: 'Ficus grande em propriedade privada. Galhos secos encostando no telhado do vizinho.',
        timestamp: Date.now() - 86400000 * 20,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'atencao'
    },
    {
        id: 1005,
        latitude: '-22.068500',
        longitude: '-46.573000',
        logradouro: 'Rua das Flores',
        referencia: 'No jardim público',
        localPlantio: 'verde',
        especie: 'Syagrus romanzoffiana',
        certeza: 'certeza',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'nenhuma',
        mesPoda: '7',
        dataUltimaPoda: '2025-07-12',
        observacoes: 'Coqueiro-queen na área verde do jardim. Muito bem conservado.',
        timestamp: Date.now() - 86400000 * 18,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'saudavel'
    },

    // ── CERTEZA DA IDENTIFICAÇÃO ──────────────────

    {
        id: 2001,
        latitude: '-22.067600',
        longitude: '-46.573800',
        logradouro: 'Rua Comendador Ribeiro',
        referencia: 'Esquina com Rua Augusta',
        localPlantio: 'calcada',
        especie: 'Mangifera indica',
        certeza: 'certeza',
        porte: 'grande',
        tronco: 'grosso',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: ['rede_eletrica'],
        intervencao: 'adequacao',
        mesPoda: '10',
        dataUltimaPoda: '2025-10-01',
        observacoes: 'Mangueira grande, frutos caindo na calçada. Identificação com certeza.',
        timestamp: Date.now() - 86400000 * 15,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'atencao'
    },
    {
        id: 2002,
        latitude: '-22.068800',
        longitude: '-46.574500',
        logradouro: 'Rua Barão do Rio Branco',
        referencia: 'Próximo à escola',
        localPlantio: 'canteiro',
        especie: 'Eugenia uniflora',
        certeza: 'palpite',
        porte: 'pequeno',
        tronco: 'fino',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: ['galhos_quebrados'],
        interferencia: [],
        intervencao: 'nenhuma',
        mesPoda: '4',
        dataUltimaPoda: '2025-04-18',
        observacoes: 'Árvore pequena, acho que é pitangueira mas não tenho certeza.',
        timestamp: Date.now() - 86400000 * 12,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'atencao'
    },
    {
        id: 2003,
        latitude: '-22.069200',
        longitude: '-46.573200',
        logradouro: 'Rua Santos Dumont',
        referencia: 'No estacionamento',
        localPlantio: 'verde',
        especie: 'Cedrela fissilis',
        certeza: 'nao_sei',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'nenhuma',
        mesPoda: '5',
        dataUltimaPoda: '2025-05-22',
        observacoes: 'Árvore no estacionamento. Não sei identificar a espécie.',
        timestamp: Date.now() - 86400000 * 10,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'saudavel'
    },

    // ── PORTE / ALTURA ────────────────────────────

    {
        id: 3001,
        latitude: '-22.067000',
        longitude: '-46.572500',
        logradouro: 'Rua São Paulo',
        referencia: 'Em frente à farmácia',
        localPlantio: 'calcada',
        especie: 'Bauhinia forficata',
        certeza: 'certeza',
        porte: 'pequeno',
        tronco: 'fino',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'nenhuma',
        mesPoda: '9',
        dataUltimaPoda: '2025-09-10',
        observacoes: 'Pata-de-vaca, árvore pequena com flores brancas bonitas.',
        timestamp: Date.now() - 86400000 * 8,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'saudavel'
    },
    {
        id: 3002,
        latitude: '-22.068300',
        longitude: '-46.574200',
        logradouro: 'Rua Paraíba',
        referencia: 'No canteiro da prefeitura',
        localPlantio: 'canteiro',
        especie: 'Caesalpinia pluviosa',
        certeza: 'certeza',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: ['inclinacao'],
        interferencia: ['iluminacao'],
        intervencao: 'adequacao',
        mesPoda: '7',
        dataUltimaPoda: '2025-07-08',
        observacoes: 'Sibipiruna com leve inclinação. Copa atingindo ponto de luz.',
        timestamp: Date.now() - 86400000 * 6,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'atencao'
    },
    {
        id: 3003,
        latitude: '-22.069500',
        longitude: '-46.573700',
        logradouro: 'Rua Minas Gerais',
        referencia: 'Em frente ao hospital',
        localPlantio: 'calcada',
        especie: 'Ficus microcarpa',
        certeza: 'certeza',
        porte: 'grande',
        tronco: 'grosso',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: ['rachaduras', 'fungos', 'galhos_secos'],
        interferencia: ['rede_eletrica', 'acessibilidade'],
        intervencao: 'urgente',
        mesPoda: '2',
        dataUltimaPoda: '2025-02-14',
        observacoes: 'Ficus grande com rachaduras no tronco, fungos e galhos secos. Risco de queda!',
        timestamp: Date.now() - 86400000 * 4,
        dataAtualizacao: Date.now(),
        status: 'critico'
    },

    // ── DIÂMETRO DO TRONCO ────────────────────────

    {
        id: 4001,
        latitude: '-22.067400',
        longitude: '-46.573900',
        logradouro: 'Rua Santa Catarina',
        referencia: 'No jardim da escola',
        localPlantio: 'verde',
        especie: 'Citharexylum myrianthum',
        certeza: 'certeza',
        porte: 'pequeno',
        tronco: 'fino',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'nenhuma',
        mesPoda: '11',
        dataUltimaPoda: '2025-11-20',
        observacoes: 'Murta com tronco fino, diâmetro até 30cm. Muito ornamental.',
        timestamp: Date.now() - 86400000 * 3,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'saudavel'
    },
    {
        id: 4002,
        latitude: '-22.068700',
        longitude: '-46.574300',
        logradouro: 'Rua Paraná',
        referencia: 'Ao lado do mercado',
        localPlantio: 'calcada',
        especie: 'Chorisia speciosa',
        certeza: 'certeza',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: ['pragas'],
        interferencia: [],
        intervencao: 'limpeza',
        mesPoda: '3',
        dataUltimaPoda: '2025-03-15',
        observacoes: 'Paineira com tronco médio (30-60cm). Presença de pragas nas folhas.',
        timestamp: Date.now() - 86400000 * 2,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'atencao'
    },

    // ── PROBLEMAS DETECTADOS ──────────────────────

    {
        id: 5001,
        latitude: '-22.067900',
        longitude: '-46.573600',
        logradouro: 'Rua Rio de Janeiro',
        referencia: 'Próximo ao mercado municipal',
        localPlantio: 'calcada',
        especie: 'Ligustrum lucidum',
        certeza: 'certeza',
        porte: 'grande',
        tronco: 'grosso',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: ['inclinacao', 'rachaduras', 'fungos'],
        interferencia: ['rede_eletrica'],
        intervencao: 'urgente',
        mesPoda: '1',
        dataUltimaPoda: '2025-01-10',
        observacoes: 'Loureiro com inclinação acentuada, rachaduras e fungos no tronco.',
        timestamp: Date.now() - 86400000 * 1,
        dataAtualizacao: Date.now(),
        status: 'critico'
    },
    {
        id: 5002,
        latitude: '-22.069100',
        longitude: '-46.574000',
        logradouro: 'Rua Goiás',
        referencia: 'No pátio da escola',
        localPlantio: 'verde',
        especie: 'Melia azedarach',
        certeza: 'certeza',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: ['broca', 'galhos_secos'],
        interferencia: [],
        intervencao: 'adequacao',
        mesPoda: '6',
        dataUltimaPoda: '2025-06-25',
        observacoes: 'Cinamomo com sinais de broca e galhos secos. Precisa de intervenção.',
        timestamp: Date.now() - 86400000 * 1,
        dataAtualizacao: Date.now(),
        status: 'atencao'
    },
    {
        id: 5003,
        latitude: '-22.068000',
        longitude: '-46.573100',
        logradouro: 'Rua Tocantins',
        referencia: 'No quintal de uma casa',
        localPlantio: 'privada',
        especie: 'Schinus terebinthifolia',
        certeza: 'certeza',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: ['erva_passarinho'],
        interferencia: [],
        intervencao: 'limpeza',
        mesPoda: '8',
        dataUltimaPoda: '2025-08-20',
        observacoes: 'Aroeira com erva-de-passarinho. Poda de limpeza necessária.',
        timestamp: Date.now() - 86400000 * 1,
        dataAtualizacao: Date.now(),
        status: 'atencao'
    },

    // ── RAÍZES ─────────────────────────────────────

    {
        id: 6001,
        latitude: '-22.067300',
        longitude: '-46.574400',
        logradouro: 'Rua Sergipe',
        referencia: 'Na esquina da praça',
        localPlantio: 'calcada',
        especie: 'Ficus obtusifolia',
        certeza: 'certeza',
        porte: 'grande',
        tronco: 'grosso',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: ['acessibilidade'],
        intervencao: 'adequacao',
        mesPoda: '4',
        dataUltimaPoda: '2025-04-12',
        observacoes: 'Ficus com raízes danificando a calçada. Risco para pedestres.',
        timestamp: Date.now() - 86400000 * 2,
        dataAtualizacao: Date.now(),
        status: 'atencao'
    },
    {
        id: 6002,
        latitude: '-22.068900',
        longitude: '-46.572900',
        logradouro: 'Rua Mato Grosso',
        referencia: 'No jardim lateral',
        localPlantio: 'verde',
        especie: 'Inga vera',
        certeza: 'certeza',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'limpeza',
        mesPoda: '5',
        dataUltimaPoda: '2025-05-30',
        observacoes: 'Ingá com raízes estrangulando base do tronco. Poda de limpeza urgente.',
        timestamp: Date.now() - 86400000 * 1,
        dataAtualizacao: Date.now(),
        status: 'atencao'
    },

    // ── INTERFERÊNCIAS URBANAS ────────────────────

    {
        id: 7001,
        latitude: '-22.067700',
        longitude: '-46.574600',
        logradouro: 'Rua Bahia',
        referencia: 'Em frente ao hospital',
        localPlantio: 'calcada',
        especie: 'Celtis iguanaea',
        certeza: 'certeza',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: ['galhos_quebrados'],
        interferencia: ['rede_eletrica'],
        intervencao: 'adequacao',
        mesPoda: '7',
        dataUltimaPoda: '2025-07-18',
        observacoes: 'Juá com galhos encostando na rede elétrica. Interferência perigosa.',
        timestamp: Date.now() - 86400000 * 3,
        dataAtualizacao: Date.now(),
        status: 'atencao'
    },
    {
        id: 7002,
        latitude: '-22.069400',
        longitude: '-46.573300',
        logradouro: 'Rua Acre',
        referencia: 'No centro da cidade',
        localPlantio: 'canteiro',
        especie: 'Platanus hispanica',
        certeza: 'certeza',
        porte: 'grande',
        tronco: 'grosso',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: ['iluminacao'],
        intervencao: 'adequacao',
        mesPoda: '9',
        dataUltimaPoda: '2025-09-02',
        observacoes: 'Plátano com copa bloqueando iluminação pública. Poda de adequação.',
        timestamp: Date.now() - 86400000 * 4,
        dataAtualizacao: Date.now(),
        status: 'atencao'
    },
    {
        id: 7003,
        latitude: '-22.068200',
        longitude: '-46.574800',
        logradouro: 'Rua Espírito Santo',
        referencia: 'No quintal vizinho',
        localPlantio: 'privada',
        especie: 'Lagerstroemia indica',
        certeza: 'certeza',
        porte: 'pequeno',
        tronco: 'fino',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: ['muros_telhados'],
        intervencao: 'nenhuma',
        mesPoda: '11',
        dataUltimaPoda: '2025-11-05',
        observacoes: 'Quaresmeira crescendo em direção ao muro do vizinho.',
        timestamp: Date.now() - 86400000 * 5,
        dataAtualizacao: Date.now(),
        status: 'atencao'
    },

    // ── INTERVENÇÃO ────────────────────────────────

    {
        id: 8001,
        latitude: '-22.067500',
        longitude: '-46.573400',
        logradouro: 'Rua Pará',
        referencia: 'No passeio público',
        localPlantio: 'calcada',
        especie: 'Erythrina speciosa',
        certeza: 'certeza',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'nenhuma',
        mesPoda: '10',
        dataUltimaPoda: '2025-10-15',
        observacoes: 'Mulungu saudável, sem necessidade de intervenção.',
        timestamp: Date.now() - 86400000 * 7,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'saudavel'
    },

    // ── MÊS IDEAL PARA PODA ───────────────────────

    {
        id: 9001,
        latitude: '-22.068600',
        longitude: '-46.573700',
        logradouro: 'Rua Ceará',
        referencia: 'Na praça da igreja',
        localPlantio: 'praca',
        especie: 'Cupania vernalis',
        certeza: 'certeza',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'limpeza',
        mesPoda: '12',
        dataUltimaPoda: '2025-12-20',
        observacoes: 'Cupaneira na praça. Poda ideal em dezembro.',
        timestamp: Date.now() - 86400000 * 9,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'atencao'
    },

    // ── STATUS ─────────────────────────────────────

    {
        id: 10001,
        latitude: '-22.069300',
        longitude: '-46.574100',
        logradouro: 'Rua Pernambuco',
        referencia: 'Na calçada larga',
        localPlantio: 'calcada',
        especie: 'Corymbia citriodora',
        certeza: 'certeza',
        porte: 'grande',
        tronco: 'grosso',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'nenhuma',
        mesPoda: '6',
        dataUltimaPoda: '2025-06-10',
        observacoes: 'Eucalipto-limão perfeito, sem nenhum problema. Status: SAUDÁVEL.',
        timestamp: Date.now() - 86400000 * 11,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'saudavel'
    },
    {
        id: 10002,
        latitude: '-22.068400',
        longitude: '-46.573900',
        logradouro: 'Rua Alagoas',
        referencia: 'No canteiro da avenida',
        localPlantio: 'canteiro',
        especie: 'Tabebuia roseoalba',
        certeza: 'certeza',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: ['galhos_secos'],
        interferencia: [],
        intervencao: 'limpeza',
        mesPoda: '8',
        dataUltimaPoda: '2025-08-05',
        observacoes: 'Ipê-branco com galhos secos. Status: ATENÇÃO.',
        timestamp: Date.now() - 86400000 * 13,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'atencao'
    },
    {
        id: 10003,
        latitude: '-22.069700',
        longitude: '-46.572700',
        logradouro: 'Rua Distrito Federal',
        referencia: 'No cruzamento perigoso',
        localPlantio: 'calcada',
        especie: 'Gleditsia amorphoides',
        certeza: 'certeza',
        porte: 'grande',
        tronco: 'grosso',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: ['inclinacao', 'rachaduras', 'fungos', 'galhos_quebrados'],
        interferencia: ['rede_eletrica', 'acessibilidade'],
        intervencao: 'urgente',
        mesPoda: '2',
        dataUltimaPoda: '2025-02-01',
        observacoes: 'Árvore CRÍTICA! Inclinação grave, rachaduras, fungos e galhos quebrados. Risco iminente.',
        timestamp: Date.now() - 86400000 * 14,
        dataAtualizacao: Date.now(),
        status: 'critico'
    },

    // ── DIVERSIDADE DE ESPÉCIES ────────────────────

    {
        id: 11001,
        latitude: '-22.067100',
        longitude: '-46.573500',
        logradouro: 'Rua Amapá',
        referencia: 'Em frente ao banco',
        localPlantio: 'calcada',
        especie: 'Aspidosperma polyneuron',
        certeza: 'certeza',
        porte: 'grande',
        tronco: 'grosso',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'nenhuma',
        mesPoda: '3',
        dataUltimaPoda: '2025-03-10',
        observacoes: 'Peroba-rosa majestosa. Espécie nativa preservada.',
        timestamp: Date.now() - 86400000 * 16,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'saudavel'
    },
    {
        id: 11002,
        latitude: '-22.068050',
        longitude: '-46.574150',
        logradouro: 'Rua Rondônia',
        referencia: 'No jardim da escola',
        localPlantio: 'verde',
        especie: 'Tibouchina granulosa',
        certeza: 'certeza',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'nenhuma',
        mesPoda: '9',
        dataUltimaPoda: '2025-09-25',
        observacoes: 'Quaresmeira roxa florindo. Bela exemplar no jardim.',
        timestamp: Date.now() - 86400000 * 17,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'saudavel'
    },
    {
        id: 11003,
        latitude: '-22.068950',
        longitude: '-46.574550',
        logradouro: 'Rua Tocantins',
        referencia: 'Na rotatória',
        localPlantio: 'canteiro',
        especie: 'Pouteria torta',
        certeza: 'palpite',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: ['galhos_secos'],
        interferencia: [],
        intervencao: 'limpeza',
        mesPoda: '4',
        dataUltimaPoda: '2025-04-28',
        observacoes: 'Árvore frutífera na rotatória. Acho que é abiu.',
        timestamp: Date.now() - 86400000 * 19,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'atencao'
    },
    {
        id: 11004,
        latitude: '-22.069600',
        longitude: '-46.573000',
        logradouro: 'Rua Roraima',
        referencia: 'No terreno baldio',
        localPlantio: 'verde',
        especie: 'Croton floribundus',
        certeza: 'certeza',
        porte: 'pequeno',
        tronco: 'fino',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'nenhuma',
        mesPoda: '7',
        dataUltimaPoda: '2025-07-15',
        observacoes: 'Sangue-de-dragão jovem. Crescendo bem no terreno verde.',
        timestamp: Date.now() - 86400000 * 21,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'saudavel'
    },
    {
        id: 11005,
        latitude: '-22.067500',
        longitude: '-46.574900',
        logradouro: 'Rua Acre',
        referencia: 'Na calçada de pedra',
        localPlantio: 'calcada',
        especie: 'Annona squamosa',
        certeza: 'certeza',
        porte: 'pequeno',
        tronco: 'fino',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: ['broca'],
        interferencia: [],
        intervencao: 'limpeza',
        mesPoda: '6',
        dataUltimaPoda: '2025-06-30',
        observacoes: 'Pinha com sinais de broca no tronco. Frutos saborosos.',
        timestamp: Date.now() - 86400000 * 22,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'atencao'
    },
    {
        id: 11006,
        latitude: '-22.068700',
        longitude: '-46.572600',
        logradouro: 'Rua Amazonas',
        referencia: 'No quintal da escola',
        localPlantio: 'privada',
        especie: 'Citrus sinensis',
        certeza: 'certeza',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: ['pragas'],
        interferencia: [],
        intervencao: 'limpeza',
        mesPoda: '8',
        dataUltimaPoda: '2025-08-22',
        observacoes: 'Laranjeira com pragas nas folhas. Produz bons frutos.',
        timestamp: Date.now() - 86400000 * 23,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'atencao'
    },
    {
        id: 11007,
        latitude: '-22.069350',
        longitude: '-46.574350',
        logradouro: 'Rua Sergipe',
        referencia: 'No passeio da praça',
        localPlantio: 'praca',
        especie: 'Hymenaea courbaril',
        certeza: 'certeza',
        porte: 'grande',
        tronco: 'grosso',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'nenhuma',
        mesPoda: '5',
        dataUltimaPoda: '2025-05-18',
        observacoes: 'Jatobá imenso na praça. Madeira muito resistente.',
        timestamp: Date.now() - 86400000 * 24,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'saudavel'
    },
    {
        id: 11008,
        latitude: '-22.067850',
        longitude: '-46.573250',
        logradouro: 'Rua Piauí',
        referencia: 'No jardim lateral',
        localPlantio: 'verde',
        especie: 'Jacaranda mimosifolia',
        certeza: 'certeza',
        porte: 'medio',
        tronco: 'medio',
        fotos: ['', '', '', '', ''],
        fotoCount: 0,
        problemas: [],
        interferencia: [],
        intervencao: 'nenhuma',
        mesPoda: '4',
        dataUltimaPoda: '2025-04-05',
        observacoes: 'Segunda jacarandá no inventário. Flores roxas incríveis.',
        timestamp: Date.now() - 86400000 * 26,
        dataAtualizacao: Date.now() - 86400000 * 1,
        status: 'saudavel'
    }
];

// =============================================
// FUNÇÃO PARA CARREGAR DADOS MOCK NO LOCALSTORAGE
// =============================================
function loadMockData() {
    const existing = localStorage.getItem(DB_KEY);
    if (existing) {
        const parsed = JSON.parse(existing);
        if (parsed.length > 0) {
            console.log(`[Mock Data] Já existem ${parsed.length} árvores no banco. Pulando carregamento.`);
            return false;
        }
    }

    localStorage.setItem(DB_KEY, JSON.stringify(MOCK_TREES));
    console.log(`[Mock Data] ${MOCK_TREES.length} árvores falsas carregadas com sucesso!`);
    return true;
}

// =============================================
// FUNÇÃO PARA LIMPAR DADOS MOCK
// =============================================
function clearMockData() {
    localStorage.removeItem(DB_KEY);
    console.log('[Mock Data] Dados limpos do localStorage.');
}

// =============================================
// FUNÇÃO PARA RECARREGAR DADOS MOCK
// =============================================
function reloadMockData() {
    localStorage.removeItem(DB_KEY);
    loadMockData();
    renderAll();
    console.log('[Mock Data] Dados recarregados. Atualize a página.');
}
